/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package View;

import Controller.ProjectController;
import Controller.TaskController;
import Model.Project;
import Model.Task;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author giova
 */
//tela de tarefa "task"
public class TaskDialogonSkin extends javax.swing.JDialog {
    //cria uma variável "controller" , que vai salvar lá na classe taskController
    TaskController controller;
    //cria uma variável "project", que vaii salvar lá na classe Project
    Project project;
    
    //cria uma variável 
    boolean  isUpdate = false ;
        int  indexTask = 0 ;
    
    // metodo costrutor
    public TaskDialogonSkin(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        //inicia os componentes desse metodo
        initComponents();
        //inicia os componentes desse metodo
        hideErrorFields();
        //inicia os componentes desse metodo
        controller = new TaskController();
        
    }//fim metodo construtor

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTooBar = new javax.swing.JPanel();
        jLabelTooBarTitle = new javax.swing.JLabel();
        jLabelTooBarSave = new javax.swing.JLabel();
        jPanelTask = new javax.swing.JPanel();
        jLabelName = new javax.swing.JLabel();
        jTextFieldName = new javax.swing.JTextField();
        jLabelDescription = new javax.swing.JLabel();
        jScrollPaneDescritpion = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabelDeadline = new javax.swing.JLabel();
        jFormattedTextFieldDeadline = new javax.swing.JFormattedTextField();
        jLabelNotes = new javax.swing.JLabel();
        jScrollPaneNotes = new javax.swing.JScrollPane();
        jTextAreaNotes = new javax.swing.JTextArea();
        jLabelNomeObrigatorio = new javax.swing.JLabel();
        jLabelPrazoObrigatorio = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelTooBar.setBackground(new java.awt.Color(0, 153, 102));
        jPanelTooBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelTooBarTitle.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabelTooBarTitle.setText("Tarefa");

        jLabelTooBarSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/View/check.png"))); // NOI18N
        jLabelTooBarSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelTooBarSaveMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanelTooBarLayout = new javax.swing.GroupLayout(jPanelTooBar);
        jPanelTooBar.setLayout(jPanelTooBarLayout);
        jPanelTooBarLayout.setHorizontalGroup(
            jPanelTooBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTooBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTooBarTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(jLabelTooBarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelTooBarLayout.setVerticalGroup(
            jPanelTooBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTooBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelTooBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTooBarTitle)
                    .addComponent(jLabelTooBarSave, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanelTask.setBackground(new java.awt.Color(255, 255, 255));
        jPanelTask.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabelName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelName.setForeground(new java.awt.Color(0, 153, 51));
        jLabelName.setText("Nome");

        jLabelDescription.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDescription.setForeground(new java.awt.Color(0, 153, 51));
        jLabelDescription.setText("Descrição");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPaneDescritpion.setViewportView(jTextAreaDescription);

        jLabelDeadline.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelDeadline.setForeground(new java.awt.Color(0, 153, 51));
        jLabelDeadline.setText("Prazo");

        jFormattedTextFieldDeadline.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.SHORT))));

        jLabelNotes.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelNotes.setForeground(new java.awt.Color(0, 102, 51));
        jLabelNotes.setText("Notas");

        jTextAreaNotes.setColumns(20);
        jTextAreaNotes.setRows(5);
        jScrollPaneNotes.setViewportView(jTextAreaNotes);

        jLabelNomeObrigatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelNomeObrigatorio.setForeground(new java.awt.Color(255, 0, 0));
        jLabelNomeObrigatorio.setText("Nome obrigatório.");

        jLabelPrazoObrigatorio.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabelPrazoObrigatorio.setForeground(new java.awt.Color(255, 0, 51));
        jLabelPrazoObrigatorio.setText("Data obrigátorio");

        javax.swing.GroupLayout jPanelTaskLayout = new javax.swing.GroupLayout(jPanelTask);
        jPanelTask.setLayout(jPanelTaskLayout);
        jPanelTaskLayout.setHorizontalGroup(
            jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaskLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelDeadline, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPaneDescritpion, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(jLabelName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldName)
                    .addComponent(jLabelNomeObrigatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelDescription, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFormattedTextFieldDeadline)
                    .addComponent(jScrollPaneNotes)
                    .addComponent(jLabelNotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPrazoObrigatorio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelTaskLayout.setVerticalGroup(
            jPanelTaskLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTaskLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelNomeObrigatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneDescritpion, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelDeadline)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextFieldDeadline, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrazoObrigatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPaneNotes, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelTooBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelTooBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelTask, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelTooBarSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelTooBarSaveMouseClicked
        // tratar possiveis erros 
        try {
            //se (os campos são validos)
            if(isFieldsValid()){
           
            //cria uma variável "task"
            Task task = new Task();
           
            //pega o id dentro da classe "project", e seta o "idProject" 
            task.setIdProject(project.getId());
        
            //pega o texto dentro da "jTextFieldName", e seta na var"name" dentro da "task"
            task.setName(jTextFieldName.getText());
        
            //pega o texto dentro da "jTextAreaDescription", e seta na var"Description" dentro da "task"
            task.setDescription(jTextAreaDescription.getText());
        
            //pega o texto dentro da "jTextAreaNotes", e seta na var"notes" dentro da "task"
            task.setNotes(jTextAreaNotes.getText());
            
            //vai seta na var"completed" false, dentro da "task"
            task.setIsCompleted(false);
        
            //pega o novo formato de data, e coloca na var"dateFormat" 
            SimpleDateFormat dateFormat =new SimpleDateFormat("dd/MM/y");
            
            //cria var"deadline" , vazia.
            Date deadline = null;
            
            //pega o texto dentro da "jFormattedTextFieldDeadline", 
            //analisa se é o mesmo formato do "dateFormat",e salva na var"deadline".
            deadline = dateFormat.parse(jFormattedTextFieldDeadline.getText());
            
            //seta as informações da deadline, dentro da var"deadline" na  "task"
            task.setDeadline(deadline);
            
            //pega a variável "task" , e salva tudo dentro do "controller", 
            controller.save(task);
            
            //exibe mensagem na "janela da tela de tarefa"
            JOptionPane.showMessageDialog(rootPane, "Tarefa salva com sucesso.");
            //fechando a janela
            this.dispose();
            
            // senão (os campos não são validos )
            }else{ 
             //inicia metodo "ocultar campos de erros"
             hideErrorFields();
                    //se (campo de nome, estiver vazio) 
                    if ( jTextFieldName . getText (). isEmpty ()) {
                        //mostra a "janela" jLabelNomeObrigatorio
                        jLabelNomeObrigatorio . setVisible ( true );
                    }
                    //se (campo de data, estiver vazio) 
                    if ( jFormattedTextFieldDeadline . getText (). isEmpty ()) {
                        // mostra a "janela" jLabelPrazoObrigatorio
                        jLabelPrazoObrigatorio . setVisible ( true );
                    }
            }
          // se deu alguma erro , mostra essa mensagem.  
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
        
         
    }//GEN-LAST:event_jLabelTooBarSaveMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Java swing".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TaskDialogonSkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TaskDialogonSkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TaskDialogonSkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TaskDialogonSkin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Criar e exibir a caixa de diálogo */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TaskDialogonSkin dialog = new TaskDialogonSkin(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField jFormattedTextFieldDeadline;
    private javax.swing.JLabel jLabelDeadline;
    private javax.swing.JLabel jLabelDescription;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelNomeObrigatorio;
    private javax.swing.JLabel jLabelNotes;
    private javax.swing.JLabel jLabelPrazoObrigatorio;
    private javax.swing.JLabel jLabelTooBarSave;
    private javax.swing.JLabel jLabelTooBarTitle;
    private javax.swing.JPanel jPanelTask;
    private javax.swing.JPanel jPanelTooBar;
    private javax.swing.JScrollPane jScrollPaneDescritpion;
    private javax.swing.JScrollPane jScrollPaneNotes;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextArea jTextAreaNotes;
    private javax.swing.JTextField jTextFieldName;
    // End of variables declaration//GEN-END:variables

    public void setProject(Project project) {
        this.project =  project;
    }
    
    // metodo para mostra que deu erro em algum campo de texto
    public  void  hideErrorFields (){
        //Não mostrar, "janela" jLabelNomeObrigatório.
        jLabelNomeObrigatorio . setVisible ( false);
        //Não mostrar, "janela" jLabelPrazoObrigatório.
        jLabelPrazoObrigatorio . setVisible ( false );
    }    
        
 // metodo verificar se o campos sao válidos       
 public  boolean  isFieldsValid (){
        //o campo de texto da data está vazio e campo de texto do nome está vazio
        return (! jTextFieldName . getText (). isEmpty ()) 
                && (! jFormattedTextFieldDeadline .
                getText (). isEmpty ());
    }
//metodo que fará atualizações das tarefas
public  void  setTasksUpdate ( Task  task ){
        //pega o nome na tarefa, coloca no jTextFieldName
        jTextFieldName. setText( task.getName());
        
        jTextAreaDescription.setText(task.getDescription());
        jTextAreaNotes. setText (task.getNotes());
        SimpleDateFormat  dateFormat = new  SimpleDateFormat ( "dd/MM/aaaa" );
        String  deadline = dateFormat .format(task. getDeadline ());
        jFormattedTextFieldDeadline . setText ("prazo");
        indexTask = task.getId();
        isUpdate= true ;
    }





}
